# Forest Night — rainy woods and warm cottage light.
foreground #e6dfcf
background #101c24
cursor #d8ad70
cursor_text_color #101c24
selection_foreground #e6dfcf
selection_background #385348
url_color #7eafb0
active_border_color #d8ad70
inactive_border_color #3b5050
active_tab_foreground #101c24
active_tab_background #d8ad70
inactive_tab_foreground #a5b5ad
inactive_tab_background #192a32
tab_bar_background #101c24
color0 #192a32
color1 #cb8580
color2 #8faa89
color3 #d8ad70
color4 #7e9fb9
color5 #aa9eaf
color6 #7eafb0
color7 #d1d6cb
color8 #758b89
color9 #e39d91
color10 #abc49e
color11 #efc58d
color12 #9cbbd1
color13 #c4b4c9
color14 #a1cdca
color15 #f2eadb
