#!/usr/bin/env bash

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

FILE="$DIR/screenshot_area_$(date +'%Y-%m-%d_%H-%M-%S').png"

# Select an area and screenshot it
grim -g "$(slurp)" "$FILE"

# Copy to clipboard
wl-copy < "$FILE"

notify-send "📸 Area screenshot saved" "$FILE and copied to clipboard"
