#!/usr/bin/env bash

# Directory to save screenshots
DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

# Filename with date
FILE="$DIR/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"

# Take full-screen screenshot
grim "$FILE"

# Copy to clipboard
wl-copy < "$FILE"

# Optional: Send a notification
notify-send "📸 Screenshot saved" "$FILE and copied to clipboard"
