#!/bin/sh
set -eu
directory="$(xdg-user-dir PICTURES 2>/dev/null || printf '%s/Pictures' "$HOME")/Screenshots"
mkdir -p "$directory"
file="$directory/screenshot_full_$(date +'%Y-%m-%d_%H-%M-%S').png"
grim "$file"
wl-copy < "$file"
notify-send 'Screenshot saved and copied' "$file"
