# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = swaybg -o \* -i /home/user/Pictures/wallpapers/j4qie3bosmgd1.jpeg -m fill
exec-once = hyprctl setcursor default 32
exec-once = waybar
exec-once = fcitx5 -d
exec-once = mako
exec-once = nm-applet --indicator
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob"
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = sunsetr

# ## Slow app launch fix
exec-once = systemctl --user import-environment
exec-once = dbus-update-activation-environment --systemd

# ## Idle configuration
exec-once = $idlehandler
