# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar
$terminal = kitty
$idlehandler = swayidle -w timeout 240 'hyprctl dispatch dpms off' timeout 300 'swaylock-fancy -e -K -p 10 -f Hack-Regular' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock-fancy -e -K -p 10 -f Hack-Regular'

# Screenshots
$shot-region = grimblast save area /home/user/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png