# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,32
envd = XCURSOR_SIZE,32
envd = QT_CURSOR_SIZE,32

# Firefox native Wayland
envd = MOZ_ENABLE_WAYLAND,1

# Qt native Wayland
envd = QT_QPA_PLATFORM,wayland;xcb
envd = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Qt dark theme
envd = QT_QPA_PLATFORMTHEME,qt5ct
envd = QT_STYLE_OVERRIDE,kvantum

# GTK native Wayland (with X11 fallback)
envd = GDK_BACKEND,wayland,x11

# GTK dark theme
envd = GTK_THEME,cachyos-nord

# Electron apps (VS Code, Discord, etc.)
envd = ELECTRON_OZONE_PLATFORM_HINT,auto

# SDL apps
envd = SDL_VIDEODRIVER,wayland
