# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# General window rules
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = size 960 540, match:title ^(Picture-in-Picture)$
windowrule = move 25%- 0, match:title ^(Picture-in-Picture)$
windowrule = float on, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = move 25%- 0, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = size 960 540, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = pin on, match:title ^(danmufloat)$
windowrule = rounding 5, match:title ^(danmufloat|termfloat)$
windowrule = animation slide right, match:class ^(kitty|Alacritty)$
windowrule = no_blur on, match:class ^(org.mozilla.firefox)$

# Dialogs & popups
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:modal 1

# Screen sharing / XWayland fixes
windowrule = immediate on, match:class ^(steam_app)(.*)$
windowrule = allows_input on, match:xwayland 1

# Idle inhibit
windowrule = idle_inhibit fullscreen, match:class ^(mpv|imv)$
windowrule = idle_inhibit always, match:class ^(steam_app)(.*)$

# Opacity for terminals
windowrule = opacity 0.95 0.85, match:class ^(kitty|Alacritty)$

# Decorations related to floating windows on workspaces 1 to 10
windowrule = border_size 2, match:float 1, match:workspace w[fv1-10]
windowrule = border_color $cachywhite, match:float 1, match:workspace w[fv1-10]
windowrule = rounding 8, match:float 1, match:workspace w[fv1-10]

# Decorations related to tiling windows on workspaces 1 to 10
windowrule = border_size 3, match:float 0, match:workspace f[1-10]
windowrule = rounding 4, match:float 0, match:workspace f[1-10]

# Workspaces Rules
workspace = w[tv1-10], gapsout:5, gapsin:3
workspace = f[1], gapsout:5, gapsin:3

# Layers Rules
layerrule = animation slide top, match:namespace logout_dialog
layerrule = animation slide down, match:namespace waybar
layerrule = animation fade, match:namespace wallpaper
layerrule = no_anim on, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = blur_popups on, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = blur on, match:namespace waybar
layerrule = xray off, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar