# Calm theme; paths are relative to the rEFInd installation.
banner themes/refind-calm/background.png
banner_scale fillscreen
big_icon_size 256
small_icon_size 64
icons_dir themes/refind-calm/icons
selection_big themes/refind-calm/selection_big.png
selection_small themes/refind-calm/selection_small.png
hideui singleuser,hints,arrows,badges
showtools hidden_tags

